name: driver_flutter
description: Movie app flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  another_flushbar: ^1.12.30
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  custom_date_range_picker: ^1.1.0
  dio: ^5.5.0+1
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  equatable: ^2.0.5
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_phosphor_icons: ^0.0.1+6
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.9
  google_maps_flutter: ^2.2.8
  image_picker: ^1.1.2
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  loader_overlay: ^4.0.1
  location: ^7.0.0
  lottie: ^3.1.2
  phosphor_flutter: ^2.1.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  stream_transform: ^2.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/logo/
    - assets/fonts/
    - assets/svg/
    - assets/animations/
